# vim ft=yaml
# travis-ci.org definition

# non-container builds don't have enough RAM to reliably compile
sudo: true
dist: trusty

language: cpp
compiler:
  - gcc
cache:
  - apt
  - ccache

addons:
  apt:
    packages: # make sure these match debian/control contents
      - bison
      - chrpath
      - cmake
      - debhelper
      - dh-apparmor
      - dpatch
      - libaio-dev
      - libboost-dev
      - libjudy-dev
      - libncurses5-dev
      - libpam0g-dev
      - libreadline-gplv2-dev
      - libssl-dev
      - libnuma-dev
      - lsb-release
      - perl
      - po-debconf
      - psmisc
      - zlib1g-dev
      - libcrack2-dev
      - libjemalloc-dev
      - devscripts # implicit for any build on Ubuntu
      
env:
  - STORAGE_ENGINE=archive
  - STORAGE_ENGINE=blackhole
  - STORAGE_ENGINE=connect
  - STORAGE_ENGINE=csv
  - STORAGE_ENGINE=example
  - STORAGE_ENGINE=federated
  - STORAGE_ENGINE=federatedx
  - STORAGE_ENGINE=heap
  - STORAGE_ENGINE=mroonga
  - STORAGE_ENGINE=myisammrg
  - STORAGE_ENGINE=oqgraph
  - STORAGE_ENGINE=sequence
  - STORAGE_ENGINE=sphinx
  - STORAGE_ENGINE=spider
  - STORAGE_ENGINE=test_sql_directory
  - STORAGE_ENGINE=tokudb
  - STORAGE_ENGINE=xtradb

script:
  - chmod +x .travis/changed_files.sh
  - .travis/changed_files.sh
  - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))  
  - ${CC} --version ; ${CXX} --version
  - cmake -DSTORAGE_ENGINE=$STORAGE_ENGINE . && make && make test
  - echo DONE TADAA

# notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#maria"
#    on_success: never # [always|never|change]
#    on_failure: never
#    template:
#      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
